# Cria o usuário e grupo padrão para os serviços Ollama
# Sintaxe: <tipo> <nome> <id> <descrição> <home> <shell>
g ollama-grid - - - -
u ollama-grid - "Ollama Grid Service User" /var/lib/ollama-grid /usr/sbin/nologin
m ollama-grid ollama-grid
m ollama-grid video
m ollama-grid render

