OLLAMA_HOST=0.0.0.0:11437

LD_LIBRARY_PATH=/usr/lib64/ollama-grid/cuda12:/usr/local/cuda/lib64

OLLAMA_LIBRARY_PATH=/usr/lib64/ollama-grid/cuda12

OLLAMA_HOME=/var/lib/ollama-grid/cuda12/

OLLAMA_LOGS=/var/log/ollama-grid/cuda12/

OLLAMA_MODELS=/var/lib/ollama-grid/models

OLLAMA_LLM_LIBRARY=cuda_v12

#CUDA_VISIBLE_DEVICES=
#PATH=

